-- Qunity — full database structure for a NEW, EMPTY Supabase project.
--
-- GENERATED by scripts/build-fresh-install.mjs from supabase/schema.sql — do
-- not edit by hand; change schema.sql and regenerate. It replays schema.sql's
-- whole history with the content inserts taken out (7 of them).
--
-- Run once, in the new project's SQL Editor, on an empty database. Then copy
-- the content (stages, workouts, exercises, challenges, tips) with
-- scripts/copy-reference-data.mjs. Do NOT also run seed.sql.

-- Qunity database schema
-- Run this once against your Supabase project (SQL Editor -> New query -> paste -> Run).

-- ============================================================================
-- TABLES
-- ============================================================================

create table public.users (
  id uuid primary key references auth.users (id) on delete cascade,
  full_name text not null,
  role text not null check (role in ('parent', 'child')),
  created_at timestamptz not null default now()
);

create table public.parents (
  id uuid primary key references public.users (id) on delete cascade,
  created_at timestamptz not null default now()
);

create table public.children (
  id uuid primary key references public.users (id) on delete cascade,
  nickname text not null,
  child_code text not null unique,
  child_code_used boolean not null default false,
  current_color text not null default 'white',
  total_points integer not null default 0,
  points_in_color integer not null default 0,
  workouts_completed_in_color integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.parent_child_links (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parents (id) on delete cascade,
  child_id uuid not null references public.children (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (parent_id, child_id)
);

create table public.bracelet_levels (
  color text primary key,
  order_index integer not null unique,
  required_workouts integer not null default 0,
  required_points integer not null default 0
);

create table public.workouts (
  id uuid primary key default gen_random_uuid(),
  title text not null,
  description text,
  recommended_duration_minutes integer,
  recommended_difficulty integer,
  color text references public.bracelet_levels (color),
  order_in_color integer,
  created_at timestamptz not null default now()
);

create table public.workout_sessions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children (id) on delete cascade,
  workout_id uuid references public.workouts (id),
  status text not null default 'in_progress' check (status in ('in_progress', 'completed', 'abandoned')),
  start_time timestamptz not null default now(),
  end_time timestamptz,
  actual_duration_minutes integer,
  created_at timestamptz not null default now()
);

create table public.workout_results (
  id uuid primary key default gen_random_uuid(),
  session_id uuid not null references public.workout_sessions (id) on delete cascade,
  activity_reported text,
  duration_reported_minutes integer,
  difficulty_reported text,
  trained_longer boolean not null default false,
  parent_trained_together boolean not null default false,
  feeling_after text,
  created_at timestamptz not null default now()
);

create table public.points_transactions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children (id) on delete cascade,
  session_id uuid references public.workout_sessions (id),
  points integer not null,
  reason text,
  created_at timestamptz not null default now()
);

create table public.challenges (
  id text primary key,
  title text not null,
  description text,
  bonus_points integer not null default 0,
  condition_type text,
  created_at timestamptz not null default now()
);

create table public.child_challenges (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children (id) on delete cascade,
  challenge_id text not null references public.challenges (id) on delete cascade,
  completed_at timestamptz,
  unique (child_id, challenge_id)
);

create table public.parent_tip_rules (
  id uuid primary key default gen_random_uuid(),
  principle text,
  condition_type text,
  condition_params jsonb not null default '{}'::jsonb,
  tip_text text not null,
  priority integer not null default 0,
  created_at timestamptz not null default now()
);

create table public.parent_tips (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parents (id) on delete cascade,
  child_id uuid not null references public.children (id) on delete cascade,
  rule_id uuid references public.parent_tip_rules (id),
  shown_at timestamptz not null default now()
);

-- ============================================================================
-- SIGNUP AUTOMATION
-- Generates a unique child_code and provisions public.users/parents/children
-- rows automatically whenever a new auth.users row is created.
-- ============================================================================

create or replace function public.generate_child_code()
returns text
language plpgsql
security definer
set search_path = public
as $$
declare
  chars text := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789'; -- no 0/O/1/I to avoid confusion
  candidate text;
  code_part text;
  i int;
  taken boolean;
begin
  loop
    code_part := '';
    for i in 1..5 loop
      code_part := code_part || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    end loop;
    candidate := 'QNTY-' || code_part;
    select exists (select 1 from public.children where child_code = candidate) into taken;
    exit when not taken;
  end loop;
  return candidate;
end;
$$;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_full_name text;
begin
  v_role := coalesce(new.raw_user_meta_data ->> 'role', 'parent');
  v_full_name := coalesce(new.raw_user_meta_data ->> 'full_name', '');

  insert into public.users (id, full_name, role)
  values (new.id, v_full_name, v_role);

  if v_role = 'parent' then
    insert into public.parents (id) values (new.id);
  elsif v_role = 'child' then
    insert into public.children (id, nickname, child_code)
    values (new.id, v_full_name, public.generate_child_code());
  end if;

  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- ROW LEVEL SECURITY
-- Rule of thumb: a child can only see their own data; a parent can only see
-- data belonging to children linked to them via parent_child_links.
-- ============================================================================

create or replace function public.is_parent_of(p_child_id uuid)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.parent_child_links
    where child_id = p_child_id and parent_id = auth.uid()
  );
$$;

alter table public.users enable row level security;
alter table public.parents enable row level security;
alter table public.children enable row level security;
alter table public.parent_child_links enable row level security;
alter table public.bracelet_levels enable row level security;
alter table public.workouts enable row level security;
alter table public.workout_sessions enable row level security;
alter table public.workout_results enable row level security;
alter table public.points_transactions enable row level security;
alter table public.challenges enable row level security;
alter table public.child_challenges enable row level security;
alter table public.parent_tip_rules enable row level security;
alter table public.parent_tips enable row level security;

-- users
create policy "users_select_self" on public.users
  for select using (id = auth.uid());
create policy "users_select_linked_children" on public.users
  for select using (public.is_parent_of(id));
create policy "users_update_self" on public.users
  for update using (id = auth.uid());

-- parents
create policy "parents_select_self" on public.parents
  for select using (id = auth.uid());

-- children
create policy "children_select_self" on public.children
  for select using (id = auth.uid());
create policy "children_select_linked" on public.children
  for select using (public.is_parent_of(id));
create policy "children_update_self" on public.children
  for update using (id = auth.uid());

-- parent_child_links
create policy "links_select_own" on public.parent_child_links
  for select using (parent_id = auth.uid() or child_id = auth.uid());
create policy "links_insert_own" on public.parent_child_links
  for insert with check (parent_id = auth.uid());

-- bracelet_levels / workouts / challenges / parent_tip_rules: shared read-only config
create policy "bracelet_levels_read" on public.bracelet_levels
  for select to authenticated using (true);
create policy "workouts_read" on public.workouts
  for select to authenticated using (true);
create policy "challenges_read" on public.challenges
  for select to authenticated using (true);
create policy "parent_tip_rules_read" on public.parent_tip_rules
  for select to authenticated using (true);

-- workout_sessions
create policy "sessions_select_own" on public.workout_sessions
  for select using (child_id = auth.uid() or public.is_parent_of(child_id));
create policy "sessions_insert_own" on public.workout_sessions
  for insert with check (child_id = auth.uid());
create policy "sessions_update_own" on public.workout_sessions
  for update using (child_id = auth.uid());

-- workout_results
create policy "results_select_own" on public.workout_results
  for select using (
    exists (
      select 1 from public.workout_sessions s
      where s.id = session_id
        and (s.child_id = auth.uid() or public.is_parent_of(s.child_id))
    )
  );
create policy "results_insert_own" on public.workout_results
  for insert with check (
    exists (
      select 1 from public.workout_sessions s
      where s.id = session_id and s.child_id = auth.uid()
    )
  );

-- points_transactions
create policy "points_select_own" on public.points_transactions
  for select using (child_id = auth.uid() or public.is_parent_of(child_id));
create policy "points_insert_own" on public.points_transactions
  for insert with check (child_id = auth.uid());

-- child_challenges
create policy "child_challenges_select_own" on public.child_challenges
  for select using (child_id = auth.uid() or public.is_parent_of(child_id));
create policy "child_challenges_insert_own" on public.child_challenges
  for insert with check (child_id = auth.uid());
create policy "child_challenges_update_own" on public.child_challenges
  for update using (child_id = auth.uid());

-- parent_tips
create policy "parent_tips_select_own" on public.parent_tips
  for select using (parent_id = auth.uid());
create policy "parent_tips_insert_own" on public.parent_tips
  for insert with check (parent_id = auth.uid());

-- ============================================================================
-- ADDED IN PROMPT 2/7 — CHILD LINKING
-- Only run the section below if you already ran everything above it in a
-- previous step. It links a parent to a child using the child's code.
--
-- A parent doesn't have RLS access to an unlinked child's row (by design),
-- so the lookup-and-link must happen atomically inside a SECURITY DEFINER
-- function rather than through ordinary client-side select/insert calls.
-- ============================================================================

create or replace function public.link_child_by_code(p_code text)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_parent_id uuid := auth.uid();
  v_child public.children%rowtype;
  v_already_linked boolean;
begin
  if v_parent_id is null then
    return jsonb_build_object('success', false, 'error', 'NOT_AUTHENTICATED');
  end if;

  select * into v_child from public.children where child_code = p_code;

  if not found then
    return jsonb_build_object('success', false, 'error', 'CODE_NOT_FOUND');
  end if;

  if v_child.child_code_used then
    return jsonb_build_object('success', false, 'error', 'CODE_ALREADY_USED');
  end if;

  select exists (
    select 1 from public.parent_child_links
    where parent_id = v_parent_id and child_id = v_child.id
  ) into v_already_linked;

  if v_already_linked then
    return jsonb_build_object('success', false, 'error', 'ALREADY_LINKED');
  end if;

  insert into public.parent_child_links (parent_id, child_id)
  values (v_parent_id, v_child.id);

  update public.children set child_code_used = true where id = v_child.id;

  return jsonb_build_object(
    'success', true,
    'child_id', v_child.id,
    'nickname', v_child.nickname
  );
end;
$$;

grant execute on function public.link_child_by_code(text) to authenticated;

-- ============================================================================
-- ADDED IN PROMPT 3/7 (follow-up) — LIFETIME WORKOUT COUNT
-- Mirrors total_points: an all-time counter that is never reset on level-up,
-- unlike workouts_completed_in_color which resets each time the child levels
-- up. Both counters are incremented together, once per completed workout
-- session, by the workout-completion flow built in a later prompt (not by
-- points.service.awardPoints, which also runs for challenge bonus points and
-- would otherwise double-count).
-- ============================================================================

alter table public.children add column total_workouts_completed integer not null default 0;

-- ============================================================================
-- ADDED IN PROMPT 4/7 — FIX recommended_difficulty COLUMN TYPE
-- Originally created as `text`; the workout flow treats it as a 1-5 numeric
-- scale (compared against the child's self-reported difficulty), so it needs
-- to be an integer. Safe to run whether or not the workouts table already
-- has rows (the USING clause casts any existing numeral text to integer).
-- ============================================================================

alter table public.workouts
  alter column recommended_difficulty type integer using recommended_difficulty::integer;

-- ============================================================================
-- ADDED IN PROMPT 6/7 (follow-up) — FIX difficulty_reported COLUMN TYPE
-- Same mistake as recommended_difficulty above, in a different table:
-- workout_results.difficulty_reported was created as `text`. Postgres/
-- PostgREST returns text columns as JSON strings, so every average computed
-- over it in JS was doing string concatenation ("3"+"4" -> "34") instead of
-- numeric addition before being coerced back to a number — producing the
-- huge, nonsensical "average difficulty" seen on the Parent Dashboard.
-- ============================================================================

alter table public.workout_results
  alter column difficulty_reported type integer using difficulty_reported::integer;

-- ============================================================================
-- ADDED IN PROMPT 6/7 (follow-up) — SWITCH SESSION DURATION TO SECONDS
-- actual_duration_minutes only ever stored whole minutes (rounded down at
-- Finish time), so any workout under 30 seconds recorded as "0" — which is
-- why "total active time" on the Parent Dashboard showed 0 for test runs.
-- Renamed to actual_duration_seconds and existing values (previously whole
-- minutes) are multiplied by 60 so old rows keep the same real-world meaning.
-- ============================================================================

alter table public.workout_sessions
  rename column actual_duration_minutes to actual_duration_seconds;

update public.workout_sessions
  set actual_duration_seconds = actual_duration_seconds * 60
  where actual_duration_seconds is not null;

-- ============================================================================
-- ADDED IN PROMPT 6/7 (follow-up) — MOBILE NAVIGATION RESTRUCTURE
-- Tracks whether a child has already seen their child_code once. The code is
-- shown inline on the Home tab only the first time (code_shown_at is null);
-- after that it is only reachable from Settings -> "הקוד שלי".
-- ============================================================================

alter table public.children add column code_shown_at timestamptz;

-- ============================================================================
-- ADDED IN PROMPT 4.5/7 — SCALE READINESS: INDEXES
-- ============================================================================

create index if not exists idx_children_total_points on public.children (total_points desc);
create index if not exists idx_workout_sessions_child_id on public.workout_sessions (child_id);
create index if not exists idx_workout_results_session_id on public.workout_results (session_id);
create index if not exists idx_points_transactions_child_id on public.points_transactions (child_id);
create index if not exists idx_child_challenges_child_id on public.child_challenges (child_id);
create index if not exists idx_parent_child_links_parent_id on public.parent_child_links (parent_id);
create index if not exists idx_parent_child_links_child_id on public.parent_child_links (child_id);

-- ============================================================================
-- ADDED IN PROMPT 4.5/7 — SCALE READINESS: ATOMIC POINT/WORKOUT-COUNT UPDATES
-- Replaces the previous "read current value in JS, add locally, write it
-- back" pattern in points.service.ts and workout.service.ts. That pattern is
-- not safe under concurrent calls: two updates that read the same starting
-- value before either writes back will silently lose one of the increments.
-- These functions do the read-and-add in a single SQL statement instead, so
-- Postgres itself guarantees the increment is atomic.
-- ============================================================================

create or replace function public.increment_child_points(p_child_id uuid, p_points integer)
returns void
language sql
security definer
set search_path = public
as $$
  update public.children
  set total_points = total_points + p_points,
      points_in_color = points_in_color + p_points
  where id = p_child_id;
$$;

grant execute on function public.increment_child_points(uuid, integer) to authenticated;

create or replace function public.increment_child_workout_counts(p_child_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.children
  set workouts_completed_in_color = workouts_completed_in_color + 1,
      total_workouts_completed = total_workouts_completed + 1
  where id = p_child_id;
$$;

grant execute on function public.increment_child_workout_counts(uuid) to authenticated;

-- ============================================================================
-- ADDED IN PROMPT 4.5/7 — i18n: preferred_language
-- ============================================================================

alter table public.users add column preferred_language text not null default 'he';

-- ============================================================================
-- ADDED IN PROMPT 4.5/7 — i18n: MULTI-LANGUAGE CONTENT (JSONB)
-- workouts/challenges/parent_tip_rules hold text written by the team, not by
-- users, so they become {"he": "...", "en": "..."} JSONB instead of plain
-- text. Existing rows are matched by their current (pre-migration) Hebrew
-- text since none of these tables have a stable natural key for title text.
-- Application code falls back to "he" if a language key is missing.
-- ============================================================================

alter table public.workouts add column title_i18n jsonb;
alter table public.workouts add column description_i18n jsonb;

update public.workouts set
  title_i18n = '{"he": "קפיצות במקום", "en": "Jumping jacks"}'::jsonb,
  description_i18n = '{"he": "חימום קליל עם קפיצות פישוק במקום.", "en": "A light warm-up with jumping jacks."}'::jsonb
  where title = 'קפיצות במקום';
update public.workouts set
  title_i18n = '{"he": "ריצה קלה בחצר", "en": "Light yard run"}'::jsonb,
  description_i18n = '{"he": "ריצה בקצב נוח סביב החצר או הגינה.", "en": "An easy-paced run around the yard or garden."}'::jsonb
  where title = 'ריצה קלה בחצר';
update public.workouts set
  title_i18n = '{"he": "מסלול מכשולים ביתי", "en": "Home obstacle course"}'::jsonb,
  description_i18n = '{"he": "בניית מסלול מכשולים פשוט עם כריות וכיסאות.", "en": "Build a simple obstacle course with pillows and chairs."}'::jsonb
  where title = 'מסלול מכשולים ביתי';
update public.workouts set
  title_i18n = '{"he": "ריקוד חופשי", "en": "Free dance"}'::jsonb,
  description_i18n = '{"he": "ריקוד חופשי לשירים אהובים במשך רבע שעה.", "en": "Free dancing to favorite songs for fifteen minutes."}'::jsonb
  where title = 'ריקוד חופשי';
update public.workouts set
  title_i18n = '{"he": "משחק כדור עם ההורה", "en": "Ball game with a parent"}'::jsonb,
  description_i18n = '{"he": "זריקות והעברות כדור יחד עם ההורה.", "en": "Throwing and passing a ball together with a parent."}'::jsonb
  where title = 'משחק כדור עם ההורה';
update public.workouts set
  title_i18n = '{"he": "קפיצה בחבל", "en": "Jump rope"}'::jsonb,
  description_i18n = '{"he": "קפיצות בחבל ברצף עם הפסקות קצרות.", "en": "Jump rope in sets with short breaks."}'::jsonb
  where title = 'קפיצה בחבל';
update public.workouts set
  title_i18n = '{"he": "אימון כוח לילדים", "en": "Kids strength workout"}'::jsonb,
  description_i18n = '{"he": "תרגילי משקל גוף: סקוואטים, פלאנק וכפיפות בטן.", "en": "Bodyweight exercises: squats, planks, and sit-ups."}'::jsonb
  where title = 'אימון כוח לילדים';
update public.workouts set
  title_i18n = '{"he": "ריצת ספרינטים קצרה", "en": "Short sprints"}'::jsonb,
  description_i18n = '{"he": "סטים של ריצות מהירות קצרות עם מנוחה.", "en": "Sets of short fast runs with rest in between."}'::jsonb
  where title = 'ריצת ספרינטים קצרה';
update public.workouts set
  title_i18n = '{"he": "מסלול אתגרים משולב", "en": "Combined challenge course"}'::jsonb,
  description_i18n = '{"he": "שילוב של ריצה, קפיצות ותרגילי כוח במסלול אחד.", "en": "A mix of running, jumping, and strength exercises in one course."}'::jsonb
  where title = 'מסלול אתגרים משולב';
update public.workouts set
  title_i18n = '{"he": "יוגה ומתיחות", "en": "Yoga and stretching"}'::jsonb,
  description_i18n = '{"he": "רצף מתיחות ותנוחות יוגה בסיסיות לגמישות.", "en": "A sequence of stretches and basic yoga poses for flexibility."}'::jsonb
  where title = 'יוגה ומתיחות';

alter table public.workouts drop column title;
alter table public.workouts drop column description;
alter table public.workouts rename column title_i18n to title;
alter table public.workouts rename column description_i18n to description;

alter table public.challenges add column title_i18n jsonb;
alter table public.challenges add column description_i18n jsonb;

update public.challenges set
  title_i18n = '{"he": "האימון הראשון", "en": "First Workout"}'::jsonb,
  description_i18n = '{"he": "השלמת האימון הראשון שלך.", "en": "You completed your first workout."}'::jsonb
  where id = 'first_workout';
update public.challenges set
  title_i18n = '{"he": "כוח ההורה", "en": "Parent Power"}'::jsonb,
  description_i18n = '{"he": "התאמנת יחד עם ההורה שלך.", "en": "You worked out together with your parent."}'::jsonb
  where id = 'parent_power';
update public.challenges set
  title_i18n = '{"he": "רצף של 3 אימונים", "en": "3 Workout Streak"}'::jsonb,
  description_i18n = '{"he": "התאמנת 3 ימים ברצף.", "en": "You worked out 3 days in a row."}'::jsonb
  where id = 'streak_3';
update public.challenges set
  title_i18n = '{"he": "רצף של 5 אימונים", "en": "5 Workout Streak"}'::jsonb,
  description_i18n = '{"he": "התאמנת 5 ימים ברצף.", "en": "You worked out 5 days in a row."}'::jsonb
  where id = 'streak_5';
update public.challenges set
  title_i18n = '{"he": "מועדון 100 הדקות", "en": "100 Minutes Club"}'::jsonb,
  description_i18n = '{"he": "צברת 100 דקות אימון במצטבר.", "en": "You accumulated 100 minutes of exercise."}'::jsonb
  where id = 'minutes_100';
update public.challenges set
  title_i18n = '{"he": "פותח הצבע", "en": "Color Starter"}'::jsonb,
  description_i18n = '{"he": "השלמת את האימון הראשון בצבע חדש.", "en": "You completed your first workout in a new color."}'::jsonb
  where id = 'color_starter';
update public.challenges set
  title_i18n = '{"he": "מסיים הצבע", "en": "Color Finisher"}'::jsonb,
  description_i18n = '{"he": "עמדת בכל הדרישות ועלית לצבע הבא.", "en": "You met every requirement and leveled up to the next color."}'::jsonb
  where id = 'color_finisher';

alter table public.challenges drop column title;
alter table public.challenges drop column description;
alter table public.challenges rename column title_i18n to title;
alter table public.challenges rename column description_i18n to description;

alter table public.parent_tip_rules add column tip_text_i18n jsonb;

update public.parent_tip_rules set tip_text_i18n = jsonb_build_object('he', tip_text, 'en', english) from (values
  ('כבר 3 ימים שהילד/ה לא התאמן/ה. זה הזמן להזכיר לו/לה שהבחירה בידיים שלו/ה - שאלו אותו/ה מתי נוח לו/לה להתחיל שוב, בלי לחץ.',
   'It has been 3 days since your child last worked out. This is a good moment to remind them the choice is theirs - ask when they would feel ready to start again, without pressure.'),
  ('עבר שבוע שלם בלי אימון. במקום להזכיר, נסו לשאול את הילד/ה מה יעזור לו/לה לחזור למסלול - התשובה שלו/ה חשובה יותר מהתזכורת שלכם.',
   'A full week has passed without a workout. Instead of reminding them, try asking what would help them get back on track - their answer matters more than your reminder.'),
  ('הילד/ה דיווח/ה על קושי גבוה באימון האחרון. הרגשות האלה לגיטימיים - הכי חשוב להכיר בהם בלי למזער, ולא בהכרח להוריד את רמת הקושי.',
   'Your child reported high difficulty in their last workout. These feelings are valid - the most important thing is acknowledging them, not necessarily lowering the difficulty.'),
  ('כמה אימונים ברצף שהילד/ה מדווח/ת שהיה קשה. שווה לשבת יחד ולשאול איך הוא/היא מרגיש/ה, בלי לנסות לתקן מיד.',
   'Several workouts in a row, your child reported that it was hard. It is worth sitting down together and asking how they feel, without rushing to fix it.'),
  ('התאמנתם יחד בפחות מ-10% מהאימונים האחרונים. ילדים לומדים הרבה מהדוגמה האישית - אימון אחד ביחד יכול לשנות המון.',
   'You have trained together in less than 10 percent of recent workouts. Kids learn a lot from personal example - one workout together can make a big difference.'),
  ('עדיין לא התאמנתם ביחד ולו פעם אחת. נסו להצטרף לאימון אחד השבוע - הנוכחות שלכם משפיעה יותר ממה שנדמה.',
   'You have not trained together even once yet. Try joining one workout this week - your presence matters more than you might think.'),
  ('הילד/ה ממשיך/ה להתאמן בעקביות אבל רמת הקושי לא עולה - וזה בסדר גמור. ההתמדה עצמה היא ההצלחה, לא בהכרח הקושי.',
   'Your child keeps training consistently, but the difficulty level is not increasing - and that is perfectly fine. The consistency itself is the success, not necessarily the difficulty.'),
  ('הילד/ה כבר השלים/ה הרבה אימונים לאורך הדרך. שווה להזכיר לו/לה (ולעצמכם) שההשקעה נמדדת בעקביות, לא רק בתגים שנפתחו.',
   'Your child has already completed a lot of workouts along the way. It is worth reminding them, and yourself, that the effort is measured by consistency, not just by badges unlocked.'),
  ('הילד/ה משלים/ה אימונים באופן סדיר אבל עוד לא פתח/ה הרבה אתגרים. כדאי להדגיש את המסע עצמו ולא רק את התגים - ההתמדה כבר הישג.',
   'Your child completes workouts regularly but has not unlocked many challenges yet. It is worth emphasizing the journey itself, not just the badges - the consistency is already an achievement.'),
  ('הילד/ה התאמן/ה הרבה החודש! זה הזמן המושלם לחגוג את העקביות עצמה, לא רק תוצאה או מעבר שלב.',
   'Your child has worked out a lot this month. This is the perfect time to celebrate the consistency itself, not just a result or leveling up.')
) as translations(hebrew, english)
where parent_tip_rules.tip_text = translations.hebrew;

alter table public.parent_tip_rules drop column tip_text;
alter table public.parent_tip_rules rename column tip_text_i18n to tip_text;
alter table public.parent_tip_rules alter column tip_text set not null;

-- ============================================================================
-- ADDED IN PROMPT 7/7 — LEADERBOARD
-- children RLS only allows a row's own child or their linked parent to see
-- it (by design — see Prompt 1/7), so there is no policy that lets a child
-- see OTHER children's rows at all. Opening a broad "select using (true)"
-- policy on children would also expose child_code to every authenticated
-- user, which would break the whole code-based linking security model (any
-- signed-in user could then link themselves to any child).
--
-- Instead, this SECURITY DEFINER function bypasses RLS internally but only
-- ever returns the four public-safe columns, pre-sorted and pre-limited —
-- nothing else in `children` is reachable through it.
-- ============================================================================

create or replace function public.get_leaderboard(p_limit integer default 20)
returns table (
  id uuid,
  nickname text,
  current_color text,
  total_points integer
)
language sql
security definer
set search_path = public
stable
as $$
  select id, nickname, current_color, total_points
  from public.children
  order by total_points desc
  limit p_limit;
$$;

grant execute on function public.get_leaderboard(integer) to authenticated;

-- ============================================================================
-- ADDED FOR JOURNEY MAP — stable upsert key for the Excel workout import
--
-- exercise_code is the human/spreadsheet-authored identifier (e.g. "white_01")
-- used by scripts/import-workouts.mjs as the upsert conflict target, instead
-- of the internal `id`, so re-importing an updated spreadsheet updates
-- existing rows rather than duplicating them. Nullable because the current
-- seed.sql sample rows predate this column; a unique index still allows
-- multiple NULLs in Postgres, so this does not need a backfill.
--
-- The (color, order_in_color) unique constraint guarantees the journey map
-- can always derive a single unambiguous station ordering per belt color.
-- ============================================================================

alter table public.workouts add column exercise_code text unique;
alter table public.workouts add constraint workouts_color_order_unique unique (color, order_in_color);

-- ============================================================================
-- ADDED FOR JOURNEY MAP — exercise bank + per-workout exercise sequence
--
-- The real workout spreadsheet composes each workout from 2-5 exercises
-- drawn from a shared exercise bank (e.g. "SQ01" = a squat variation), not a
-- single freeform title/description. Storing this as two related tables
-- (rather than flattening it into workouts.description) keeps the real
-- structure available for future screens (e.g. "show me the exercises in
-- this workout") without another migration.
-- ============================================================================

create table public.exercises (
  id text primary key, -- stable code from the spreadsheet's exercise_bank sheet, e.g. "SQ01"
  pattern_en text,
  pattern_he text,
  name_he text not null,
  name_en text not null,
  description_he text,
  difficulty_tip_he text,
  created_at timestamptz not null default now()
);

create table public.workout_exercises (
  id uuid primary key default gen_random_uuid(),
  workout_id uuid not null references public.workouts (id) on delete cascade,
  slot_number integer not null,
  exercise_id text not null references public.exercises (id),
  unique (workout_id, slot_number)
);

alter table public.exercises enable row level security;
alter table public.workout_exercises enable row level security;

create policy "exercises_read" on public.exercises
  for select to authenticated using (true);
create policy "workout_exercises_read" on public.workout_exercises
  for select to authenticated using (true);

-- ============================================================================
-- ADDED FOR INTERVAL WORKOUT TIMER
--
-- Per-belt Tabata-style structure (from the spreadsheet's levels_overview
-- sheet: rounds, work_sec, rest_sec) driving WorkoutRunner's countdown
-- timer. Nullable until scripts/import-workouts.mjs populates them, so the
-- app falls back to the old plain stopwatch when they're absent.
-- ============================================================================

alter table public.bracelet_levels add column interval_rounds integer;
alter table public.bracelet_levels add column interval_work_seconds integer;
alter table public.bracelet_levels add column interval_rest_seconds integer;

-- ============================================================================
-- ADDED FOR GENDERED TIP PHRASING
--
-- Same underlying value for both roles ("male"/"female") — the signup form
-- just shows different labels (הורה: אמא/אבא, ילד/ה: זכר/נקבה) depending on
-- role. Nullable for existing accounts created before this column existed.
--
-- Used to pick the correct Hebrew grammatical gender when rendering
-- parent_tip_rules.tip_text (see resolveGenderedText in i18n-content.ts) —
-- tips describe the CHILD's behavior, so it's the child's gender that
-- matters here, not the parent's.
-- ============================================================================

alter table public.users add column gender text check (gender in ('male', 'female'));

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_role text;
  v_full_name text;
  v_gender text;
begin
  v_role := coalesce(new.raw_user_meta_data ->> 'role', 'parent');
  v_full_name := coalesce(new.raw_user_meta_data ->> 'full_name', '');
  v_gender := new.raw_user_meta_data ->> 'gender';

  insert into public.users (id, full_name, role, gender)
  values (new.id, v_full_name, v_role, v_gender);

  if v_role = 'parent' then
    insert into public.parents (id) values (new.id);
  elsif v_role = 'child' then
    insert into public.children (id, nickname, child_code)
    values (new.id, v_full_name, public.generate_child_code());
  end if;

  return new;
end;
$$;

-- ============================================================================
-- ADDED FOR GENDERED TIP PHRASING — rewrite tip_text.he as ICU gender-select
--
-- Only 8 of the 10 tips reference the child directly (הילד/ה, התאמן/ה, ...);
-- low_parent_participation and zero_parent_participation only address the
-- parent in plural/neutral forms and are left as-is. "other" keeps the
-- original slash-form as a safety net if gender is ever null/unrecognized.
-- resolveGenderedText() (src/lib/i18n-content.ts) evaluates this syntax;
-- plain strings without "{gender" pass through unchanged, so this is safe
-- even before every row is converted.
-- ============================================================================

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {כבר 3 ימים שהילד לא התאמן. זה הזמן להזכיר לו שהבחירה בידיים שלו - שאלו אותו מתי נוח לו להתחיל שוב, בלי לחץ.} female {כבר 3 ימים שהילדה לא התאמנה. זה הזמן להזכיר לה שהבחירה בידיים שלה - שאלו אותה מתי נוח לה להתחיל שוב, בלי לחץ.} other {כבר 3 ימים שהילד/ה לא התאמן/ה. זה הזמן להזכיר לו/לה שהבחירה בידיים שלו/ה - שאלו אותו/ה מתי נוח לו/לה להתחיל שוב, בלי לחץ.}}'::text
))
where condition_type = 'no_workout_3_days';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {עבר שבוע שלם בלי אימון. במקום להזכיר, נסו לשאול את הילד מה יעזור לו לחזור למסלול - התשובה שלו חשובה יותר מהתזכורת שלכם.} female {עבר שבוע שלם בלי אימון. במקום להזכיר, נסו לשאול את הילדה מה יעזור לה לחזור למסלול - התשובה שלה חשובה יותר מהתזכורת שלכם.} other {עבר שבוע שלם בלי אימון. במקום להזכיר, נסו לשאול את הילד/ה מה יעזור לו/לה לחזור למסלול - התשובה שלו/ה חשובה יותר מהתזכורת שלכם.}}'::text
))
where condition_type = 'no_workout_7_days';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {הילד דיווח על קושי גבוה באימון האחרון. הרגשות האלה לגיטימיים - הכי חשוב להכיר בהם בלי למזער, ולא בהכרח להוריד את רמת הקושי.} female {הילדה דיווחה על קושי גבוה באימון האחרון. הרגשות האלה לגיטימיים - הכי חשוב להכיר בהם בלי למזער, ולא בהכרח להוריד את רמת הקושי.} other {הילד/ה דיווח/ה על קושי גבוה באימון האחרון. הרגשות האלה לגיטימיים - הכי חשוב להכיר בהם בלי למזער, ולא בהכרח להוריד את רמת הקושי.}}'::text
))
where condition_type = 'high_difficulty_reported';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {כמה אימונים ברצף שהילד מדווח שהיה קשה. שווה לשבת יחד ולשאול איך הוא מרגיש, בלי לנסות לתקן מיד.} female {כמה אימונים ברצף שהילדה מדווחת שהיה קשה. שווה לשבת יחד ולשאול איך היא מרגישה, בלי לנסות לתקן מיד.} other {כמה אימונים ברצף שהילד/ה מדווח/ת שהיה קשה. שווה לשבת יחד ולשאול איך הוא/היא מרגיש/ה, בלי לנסות לתקן מיד.}}'::text
))
where condition_type = 'negative_feeling_streak';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {הילד ממשיך להתאמן בעקביות אבל רמת הקושי לא עולה - וזה בסדר גמור. ההתמדה עצמה היא ההצלחה, לא בהכרח הקושי.} female {הילדה ממשיכה להתאמן בעקביות אבל רמת הקושי לא עולה - וזה בסדר גמור. ההתמדה עצמה היא ההצלחה, לא בהכרח הקושי.} other {הילד/ה ממשיך/ה להתאמן בעקביות אבל רמת הקושי לא עולה - וזה בסדר גמור. ההתמדה עצמה היא ההצלחה, לא בהכרח הקושי.}}'::text
))
where condition_type = 'difficulty_plateau';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {הילד כבר השלים הרבה אימונים לאורך הדרך. שווה להזכיר לו (ולעצמכם) שההשקעה נמדדת בעקביות, לא רק בתגים שנפתחו.} female {הילדה כבר השלימה הרבה אימונים לאורך הדרך. שווה להזכיר לה (ולעצמכם) שההשקעה נמדדת בעקביות, לא רק בתגים שנפתחו.} other {הילד/ה כבר השלים/ה הרבה אימונים לאורך הדרך. שווה להזכיר לו/לה (ולעצמכם) שההשקעה נמדדת בעקביות, לא רק בתגים שנפתחו.}}'::text
))
where condition_type = 'high_total_effort_reminder';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {הילד משלים אימונים באופן סדיר אבל עוד לא פתח הרבה אתגרים. כדאי להדגיש את המסע עצמו ולא רק את התגים - ההתמדה כבר הישג.} female {הילדה משלימה אימונים באופן סדיר אבל עוד לא פתחה הרבה אתגרים. כדאי להדגיש את המסע עצמו ולא רק את התגים - ההתמדה כבר הישג.} other {הילד/ה משלים/ה אימונים באופן סדיר אבל עוד לא פתח/ה הרבה אתגרים. כדאי להדגיש את המסע עצמו ולא רק את התגים - ההתמדה כבר הישג.}}'::text
))
where condition_type = 'low_challenge_unlock_rate';

update public.parent_tip_rules
set tip_text = jsonb_set(tip_text, '{he}', to_jsonb(
  '{gender, select, male {הילד התאמן הרבה החודש! זה הזמן המושלם לחגוג את העקביות עצמה, לא רק תוצאה או מעבר שלב.} female {הילדה התאמנה הרבה החודש! זה הזמן המושלם לחגוג את העקביות עצמה, לא רק תוצאה או מעבר שלב.} other {הילד/ה התאמן/ה הרבה החודש! זה הזמן המושלם לחגוג את העקביות עצמה, לא רק תוצאה או מעבר שלב.}}'::text
))
where condition_type = 'consistent_monthly_activity';

-- ============================================================================
-- ADDED FOR PROMPT 8 — 50-tip expansion
--
-- trigger_source records which channel actually showed a tip: 'auto' (the
-- normal getRelevantTips() evaluation on dashboard load), 'manual' (parent
-- picked it from the "What's happening now" accordion), or 'test' (the
-- temporary manual-test-mode number field). Defaults to 'auto' so existing
-- rows don't need backfilling.
-- ============================================================================

alter table public.parent_tips
  add column trigger_source text not null default 'auto'
    check (trigger_source in ('auto', 'manual', 'test'));

-- ============================================================================
-- CATEGORY 1 — automatic, cumulative-data conditions (7 condition_types,
-- 8 rows since consecutive_day_streak is shared by #35/#44 and
-- abandoned_session is also tagged into the category-3 menu below).
-- ============================================================================

-- [fresh install] content insert into public.parent_tip_rules removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- ============================================================================
-- CATEGORY 2 — questionnaire-based, single most-recent-session conditions
-- (7 condition_types, 11 rows — duals share a condition_type on purpose so
-- getRelevantTips shows them together; see tips.service.ts).
-- ============================================================================

-- [fresh install] content insert into public.parent_tip_rules removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- ============================================================================
-- CATEGORY 3 — parent-initiated "What's happening now" accordion menu
-- (34 rows, condition_type='manual_selection' — never auto-evaluated by
-- getRelevantTips; the UI queries condition_params->>'menuGroup' directly).
-- Priority is irrelevant here (not competing for a slot) so left at 0.
-- ============================================================================

-- [fresh install] content insert into public.parent_tip_rules removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- ============================================================================
-- ADDED FOR TIP LIKE/DISMISS FEATURE
--
-- One counter per tip overall (not per-child, per the product decision —
-- we only want to know how often a card is liked in general, not who liked
-- it). Incremented via a security-definer RPC rather than a raw UPDATE RLS
-- policy, since parents otherwise have no write access to parent_tip_rules
-- (team-authored content) and this keeps the writable surface to exactly
-- one counter column.
-- ============================================================================

alter table public.parent_tip_rules add column like_count integer not null default 0;

create or replace function public.increment_tip_like_count(p_rule_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.parent_tip_rules
  set like_count = like_count + 1
  where id = p_rule_id;
$$;

grant execute on function public.increment_tip_like_count(uuid) to authenticated;

-- ============================================================================
-- ADDED FOR POINTS HEADROOM
--
-- required_points used to equal exactly base_points(20) * required_workouts
-- for every color, i.e. zero headroom for any bonus (trained_longer +5,
-- harder_than_recommended +5, parent_together +10, first_in_color +10 —
-- see points.service.ts). The moment a child earned even one bonus,
-- points_in_color raced past required_points before workouts_completed_in_color
-- reached required_workouts, so the dashboard showed "0 points left" while
-- a workout was still required (progression needs BOTH thresholds — see
-- evaluateProgression). Bumped required_points to 1.5x (30/workout) so
-- typical bonus-earning play doesn't hit 0 early.
-- ============================================================================

update public.bracelet_levels set required_points = 300 where color = 'white';
update public.bracelet_levels set required_points = 420 where color = 'orange';
update public.bracelet_levels set required_points = 540 where color = 'green';
update public.bracelet_levels set required_points = 660 where color = 'blue';
update public.bracelet_levels set required_points = 780 where color = 'purple';

-- ============================================================================
-- ADDED FOR EXERCISE IMAGES
--
-- Nullable — the UI only renders an <img> when this is set, so exercises
-- without one just show as before. Upload the image to Supabase Storage
-- (or any public host) and update this column with the resulting URL; see
-- the app's reply for the step-by-step.
-- ============================================================================

alter table public.exercises add column image_url text;

-- ============================================================================
-- ADDED FOR REPEATABLE ("TYPE B") CHALLENGES
--
-- Two kinds of challenges now exist, distinguished by challenge_type:
--   'condition'          — the original 7 challenges: auto-detected from
--                           cumulative activity (first workout, streaks,
--                           etc — see challenge.service.ts's isConditionMet),
--                           unlock and complete in the same moment, one-time.
--   'repeatable_workout' — a challenging "workout" of its own (e.g. a
--                           stairs climb) that unlocks when a child FINISHES
--                           a given belt color (unlock_color) and can then be
--                           performed any number of times, each time
--                           awarding bonus_points again. Does not appear on
--                           the journey map — only in the Challenges tab.
--
-- child_challenges keeps tracking one-time UNLOCK state for both kinds (for
-- 'condition' rows, unlocking IS completing, so completed_at already means
-- that; for 'repeatable_workout' rows it just marks "became available" —
-- the actual per-attempt history lives in challenge_sessions below).
-- ============================================================================

alter table public.challenges
  add column challenge_type text not null default 'condition'
    check (challenge_type in ('condition', 'repeatable_workout'));
alter table public.challenges
  add column unlock_color text references public.bracelet_levels (color);

create table public.challenge_sessions (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children (id) on delete cascade,
  challenge_id text not null references public.challenges (id) on delete cascade,
  status text not null default 'completed' check (status in ('in_progress', 'completed')),
  start_time timestamptz not null default now(),
  end_time timestamptz,
  actual_duration_seconds integer,
  difficulty_reported integer,
  feeling_after text,
  parent_trained_together boolean not null default false,
  points_awarded integer,
  created_at timestamptz not null default now()
);

alter table public.challenge_sessions enable row level security;

create policy "challenge_sessions_select_own" on public.challenge_sessions
  for select using (child_id = auth.uid() or public.is_parent_of(child_id));
create policy "challenge_sessions_insert_own" on public.challenge_sessions
  for insert with check (child_id = auth.uid());
create policy "challenge_sessions_update_own" on public.challenge_sessions
  for update using (child_id = auth.uid());

-- 5 sample repeatable challenges, one per color, for testing the flow end
-- to end. Content/points are placeholders — easy to edit later since this is
-- all DB-driven (see the challenges DB-unification change).
-- [fresh install] content insert into public.challenges removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- ============================================================================
-- ADDED FOR CHALLENGE POINTS ISOLATION
--
-- Repeatable ("type B") challenges can be done any number of times, so
-- their points must NOT feed points_in_color (the belt-progression gate —
-- see progression.service.ts's calculateProgressPercent) or they'd inflate
-- the displayed progress bar without any matching real workout progress.
-- They still count toward total_points (lifetime score / leaderboard).
-- ============================================================================

create or replace function public.increment_child_total_points_only(p_child_id uuid, p_points integer)
returns void
language sql
security definer
set search_path = public
as $$
  update public.children
  set total_points = total_points + p_points
  where id = p_child_id;
$$;

grant execute on function public.increment_child_total_points_only(uuid, integer) to authenticated;

-- ============================================================================
-- ADDED FOR TIP PRINCIPLE I18N
--
-- parent_tip_rules.principle was still plain English text (e.g. "Empowering
-- Framework") even after tip_text itself became {"he", "en"} JSONB — it was
-- rendered as-is in a Hebrew-only UI. Same migration pattern as
-- workouts/challenges/parent_tip_rules.tip_text: add the _i18n column,
-- backfill by matching the current text, drop + rename. "Personal Example"
-- (used by the two original low/zero_parent_participation rows) and
-- "Personal Example & Praise" (used by every Prompt 8 row) are the same
-- principle under two names that drifted apart — both map to the same
-- Hebrew text here. English is kept for whenever the UI supports it.
-- ============================================================================

alter table public.parent_tip_rules add column principle_i18n jsonb;

update public.parent_tip_rules
set principle_i18n = jsonb_build_object('he', 'מסגרת מעצימה', 'en', 'Empowering Framework')
where principle = 'Empowering Framework';

update public.parent_tip_rules
set principle_i18n = jsonb_build_object('he', 'פוקוס על הדרך', 'en', 'Focus On The Journey')
where principle = 'Focus On The Journey';

update public.parent_tip_rules
set principle_i18n = jsonb_build_object('he', 'אמונה משחררת', 'en', 'Liberating Belief')
where principle = 'Liberating Belief';

update public.parent_tip_rules
set principle_i18n = jsonb_build_object('he', 'דוגמא אישית והכוונה', 'en', 'Personal Example & Praise')
where principle in ('Personal Example & Praise', 'Personal Example');

update public.parent_tip_rules
set principle_i18n = jsonb_build_object('he', 'מותר להרגיש הכל', 'en', 'All Feelings Are Allowed')
where principle = 'All Feelings Are Allowed';

alter table public.parent_tip_rules drop column principle;
alter table public.parent_tip_rules rename column principle_i18n to principle;

-- ============================================================================
-- ADDED FOR PARENT/CHILD MODE SWITCHING
--
-- Lets a parent create a child profile directly (no separate email/signup
-- for the child) and switch this device between "Parent Mode" and "Child
-- Mode" without a real login each time. The child still gets a completely
-- normal auth.users account under the hood (via public.handle_new_user(),
-- same trigger as always) — it's just created and held by the app instead
-- of the child registering it themselves, and its login is never shown to
-- anyone.
--
-- parents.pin_hash: a parent-chosen 4-digit PIN (salted+hashed in app code,
-- see src/lib/pin.ts — never stored in plaintext) that gates returning from
-- Child Mode back to Parent Mode on the SAME device. It is not a Supabase
-- Auth credential and cannot log in as the parent from anywhere else — the
-- app restores the parent's session from tokens it cached client-side at
-- switch time, using the PIN only as a local unlock gate.
--
-- child_credentials: the child's hidden auto-generated login. Deliberately
-- has NO RLS policies at all (RLS is enabled with zero grants = default
-- deny for every role) so it is reachable only via the service-role key
-- from server-side code (src/lib/supabase/admin.ts) — never through the
-- normal client, by a parent, or by the child themselves.
-- ============================================================================

alter table public.parents add column pin_hash text;

create policy "parents_update_self" on public.parents
  for update using (id = auth.uid());

create table public.child_credentials (
  child_id uuid primary key references public.children (id) on delete cascade,
  hidden_email text not null unique,
  hidden_password text not null,
  created_at timestamptz not null default now()
);

alter table public.child_credentials enable row level security;
-- No policies added on purpose — see comment above.

-- ============================================================================
-- ADDED FOR QR/CODE DEVICE PAIRING
--
-- Lets a child's OWN phone get a session for their existing hidden account
-- (see child_credentials above) without ever seeing an email or password:
-- the parent generates a short-lived, single-use code from their device;
-- the child's device redeems it (by scanning a QR that encodes a /pair/<token>
-- link, or by typing the 6-digit `code` at /pair) and gets signed in.
--
-- token: long random string, embedded in the QR's URL — effectively
-- impossible to guess, so it alone is enough proof of possessing the QR.
-- code: short 6-digit string for manual entry — NOT guaranteed globally
-- unique (only checked among currently-active codes at creation time), so
-- redeeming it always filters on used_at is null and expires_at > now().
--
-- Same no-RLS-policies pattern as child_credentials: reachable only via the
-- service-role key from server-side code, never through the normal client.
-- ============================================================================

create table public.pairing_codes (
  id uuid primary key default gen_random_uuid(),
  child_id uuid not null references public.children (id) on delete cascade,
  token text not null unique,
  code text not null,
  created_at timestamptz not null default now(),
  expires_at timestamptz not null,
  used_at timestamptz
);

alter table public.pairing_codes enable row level security;
-- No policies added on purpose — see comment above.

-- ============================================================================
-- ADDED FOR CHILD AGE
-- Collected on the "יצירת פרופיל ילד חדש" screen (createChildProfile) — not
-- used by any progression/workout logic yet, purely informational for now.
-- Nullable since every child created before this exists without one.
-- ============================================================================

alter table public.children add column age integer;

-- ============================================================================
-- ADDED FOR PARTIAL-COMPLETION POINTS, STATION REPLAY AND PER-POWER CHALLENGES
--
-- completion_percent: how much of the planned time the child actually did
--   (0-100), set when the questionnaire is submitted. NULL on sessions from
--   before this existed — treated as 100 (full) everywhere.
-- station_number: the child's 1-based position within the workout's color
--   (same numbering as the journey map's local_number). Lets the map/summary
--   find "the session(s) for station N" directly instead of guessing by
--   order of completion.
-- is_replay: a repeat of a station that was already passed. Replays never
--   advance workouts_completed_in_color or points_in_color, but still count
--   as real workouts for total_workouts_completed and for the parent.
-- ============================================================================

alter table public.workout_sessions
  add column completion_percent integer check (completion_percent between 0 and 100),
  add column station_number integer,
  add column is_replay boolean not null default false;

-- Every session before this change was a regular (non-replay) one, so the
-- station number is simply the order in which the child completed workouts
-- of that color — the same ordinal rule the journey map used until now.
update public.workout_sessions s
set station_number = ranked.rn
from (
  select ws.id,
         row_number() over (partition by ws.child_id, w.color order by ws.start_time) as rn
  from public.workout_sessions ws
  join public.workouts w on w.id = ws.workout_id
  where ws.status = 'completed'
) ranked
where s.id = ranked.id;

-- Replays count toward the lifetime workout total (what the parent sees) but
-- not toward the color's progress counter.
create or replace function public.increment_child_total_workouts_only(p_child_id uuid)
returns void
language sql
security definer
set search_path = public
as $$
  update public.children
  set total_workouts_completed = total_workouts_completed + 1
  where id = p_child_id;
$$;

grant execute on function public.increment_child_total_workouts_only(uuid) to authenticated;

-- One challenge per power ("קבלת כוח X"), unlocked the moment the power is
-- revealed at the start of that color's first workout. Replaces the single
-- "color_starter" challenge.
-- [fresh install] content insert into public.challenges removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- Children who already passed a color (or are past the first workout of
-- their current one) have already seen that power: give them its challenge
-- without any extra bonus points.
-- [fresh install] content insert into public.child_challenges removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- The old single challenge is superseded (its child_challenges rows cascade).
delete from public.challenges where id = 'color_starter';

-- ============================================================================
-- ADDED FOR LEADERBOARD ORDERING BY STAGE FIRST, POINTS AS TIE-BREAKER
--
-- Ranking is now (bracelet color order desc, total_points desc) instead of
-- total_points alone: a child further along the color track always outranks
-- one who is earlier, no matter how many points the earlier child has piled
-- up (e.g. from repeating workouts) — points only break ties within the
-- same color. Same signature/return shape as before, so no client change.
-- ============================================================================

create or replace function public.get_leaderboard(p_limit integer default 20)
returns table (
  id uuid,
  nickname text,
  current_color text,
  total_points integer
)
language sql
security definer
set search_path = public
stable
as $$
  select c.id, c.nickname, c.current_color, c.total_points
  from public.children c
  join public.bracelet_levels bl on bl.color = c.current_color
  order by bl.order_index desc, c.total_points desc
  limit p_limit;
$$;

-- ============================================================================
-- ADDED FOR CHALLENGES-SCREEN REVEAL TRACKING
--
-- A one-time challenge is revealed twice: first in the popup on the workout
-- result screen, then once more on the challenges screen, where its mystery
-- box opens by itself on the child's next visit. revealed_at records that
-- second reveal. Null means "not opened there yet". The app sets it only
-- after the box has actually flipped open, through the existing
-- child_challenges_update_own policy, so no new policy is needed.
--
-- Everything already earned before this change counts as revealed, so no
-- child gets a flood of old boxes opening at once.
-- ============================================================================

alter table public.child_challenges add column revealed_at timestamptz;

update public.child_challenges
set revealed_at = coalesce(completed_at, now());

-- ============================================================================
-- ADDED FOR THE PARENT WORKOUTS SCREEN TIP
--
-- The workouts screen shows one tip read off the child's last two weeks of
-- workouts. These rows hold its texts; condition_params.screen = 'history'
-- keeps them off the home screen's tip list (their condition_types have no
-- entry in TIP_CONDITION_REGISTRY) and out of the "what's happening now"
-- menu (no menuGroup). Which situations apply is decided in code
-- (matchHistoryConditions in workout-history.service.ts); when several do,
-- the highest priority wins, so reordering is just editing priority here.
-- {name} is the child's name; the Hebrew picks the child's gender.
-- ============================================================================

-- [fresh install] content insert into public.parent_tip_rules removed here —
-- the content is copied from the old project by scripts/copy-reference-data.mjs.

-- ============================================================================
-- ADDED FOR GENDERED CHALLENGE DESCRIPTIONS
--
-- The stair challenges' Hebrew descriptions were masculine only ("עלה 100
-- מדרגות"). Rewritten as ICU gender-select like parent_tip_rules.tip_text;
-- the app renders them with resolveGenderedText (masculine when the child's
-- gender is unknown), and plain text still passes through unchanged.
-- ============================================================================

update public.challenges
set description = jsonb_set(description, '{he}', to_jsonb('{gender, select, female {עלי 100 מדרגות ברצף, בקצב שנוח לך.} other {עלה 100 מדרגות ברצף, בקצב שנוח לך.}}'::text))
where id = 'stairs_white';

update public.challenges
set description = jsonb_set(description, '{he}', to_jsonb('{gender, select, female {עלי 200 מדרגות ברצף, בקצב שנוח לך.} other {עלה 200 מדרגות ברצף, בקצב שנוח לך.}}'::text))
where id = 'stairs_orange';

update public.challenges
set description = jsonb_set(description, '{he}', to_jsonb('{gender, select, female {עלי 300 מדרגות ברצף, בקצב שנוח לך.} other {עלה 300 מדרגות ברצף, בקצב שנוח לך.}}'::text))
where id = 'stairs_green';

update public.challenges
set description = jsonb_set(description, '{he}', to_jsonb('{gender, select, female {עלי 400 מדרגות ברצף, בקצב שנוח לך.} other {עלה 400 מדרגות ברצף, בקצב שנוח לך.}}'::text))
where id = 'stairs_blue';

update public.challenges
set description = jsonb_set(description, '{he}', to_jsonb('{gender, select, female {עלי 500 מדרגות ברצף, בקצב שנוח לך.} other {עלה 500 מדרגות ברצף, בקצב שנוח לך.}}'::text))
where id = 'stairs_purple';

-- ============================================================================
-- ADDED FOR THE PARENT HOME SCREEN'S SHORT TIPS
--
-- The parent home screen shows a short sentence to say to the child, with a
-- "כי…" line under it saying why it shows today. Both are {"he": "..."} like
-- tip_text and use the same ICU syntax: {gender} for the child, {parentGender}
-- for the parent's own words, and {name}, {days}, {count} filled in from the
-- child's data. Only the auto-evaluated tips have them; the rest stay null.
-- ============================================================================

alter table public.parent_tip_rules
  add column if not exists short_text jsonb,
  add column if not exists reason_text jsonb;

-- abandoned_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'רוצה לנסות שוב יחד? דקה אחת ואז נחליט.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} עצרה באמצע האימון האחרון} other {כי {name} עצר באמצע האימון האחרון}}')
where id = 'f2b0fa50-46ec-4f2f-8f7c-db14eee536d3';

-- comeback_after_break
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'יפה שחזרת, כל חזרה מחזקת אותך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} חזרה להתאמן אחרי {days} ימים של הפסקה} other {כי {name} חזר להתאמן אחרי {days} ימים של הפסקה}}')
where id = '451c414a-7c48-461f-9c1c-71dd31814acf';

-- consecutive_day_streak
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'איך הצלחת להתמיד? זה כוח אמיתי.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} התאמנה {days} ימים ברצף} other {כי {name} התאמן {days} ימים ברצף}}')
where id = '8927ab22-217c-4bf1-8ca4-6522163673da';

-- consecutive_day_streak
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'ראיתי שלא ויתרת, זה כוח רצון.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} התאמנה {days} ימים ברצף} other {כי {name} התאמן {days} ימים ברצף}}')
where id = 'f1704326-99fd-4c59-898e-e62fbb31f0ca';

-- consistent_monthly_activity
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'ראיתי כמה התמדת החודש. איך עשית את זה?'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} השלימה {count} אימונים החודש} other {כי {name} השלים {count} אימונים החודש}}')
where id = '4979769d-6868-4f58-a830-63517f70c012';

-- difficulty_high_and_positive_feeling
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'מה עזר לך לא לעצור?'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהיה מאתגר, ובכל זאת סיימה בהרגשה טובה} other {כי {name} סימן שהיה מאתגר, ובכל זאת סיים בהרגשה טובה}}')
where id = '6426e1f9-ffa3-4867-93b7-202c763465ad';

-- difficulty_high_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'הניסיון חשוב יותר מהתוצאה.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה מאתגר} other {כי {name} סימן שהאימון האחרון היה מאתגר}}')
where id = '60f2484e-d38b-4307-9c94-95e34e2d2a2b';

-- difficulty_high_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'ומה בכל זאת עשית? כל צעד הוא הישג.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה מאתגר} other {כי {name} סימן שהאימון האחרון היה מאתגר}}')
where id = '9dd41fb1-26e0-420a-8a22-a74218184f1c';

-- difficulty_high_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'זה לא פשוט, אבל אני {parentGender, select, female {מאמינה} other {מאמין}} בך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה מאתגר} other {כי {name} סימן שהאימון האחרון היה מאתגר}}')
where id = '70a49fc7-7b5b-4171-b2e6-4311ca0047f7';

-- difficulty_plateau
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {את ממשיכה להתאמן, וזו ההצלחה האמיתית.} other {אתה ממשיך להתאמן, וזו ההצלחה האמיתית.}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} מתאמנת בעקביות באותה רמת קושי} other {כי {name} מתאמן בעקביות באותה רמת קושי}}')
where id = '3b4eb51a-ec06-4fb1-a1a4-d1cd5e2f5017';

-- difficulty_very_hard_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'מה למדת על עצמך מהאימון הקשה?'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה קשה מאוד} other {כי {name} סימן שהאימון האחרון היה קשה מאוד}}')
where id = 'a4c72848-7d98-4dfa-84ce-4624add352da';

-- difficulty_very_hard_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {כאן בדיוק מתחזק השריר שלך. אל תוותרי.} other {כאן בדיוק מתחזק השריר שלך. אל תוותר.}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה קשה מאוד} other {כי {name} סימן שהאימון האחרון היה קשה מאוד}}')
where id = '4dcea5af-05ed-4d9f-89a1-759dd9eb356b';

-- feeling_exhausted_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'זה היה המון. מגיעה לך מנוחה אמיתית.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} הרגישה מותשת אחרי האימון האחרון} other {כי {name} הרגיש מותש אחרי האימון האחרון}}')
where id = '169ac51a-1925-4a17-abb1-91fdec74fc12';

-- feeling_frustrated_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'זה מתסכל כשלא מצליחים, אני {parentGender, select, female {מבינה} other {מבין}} אותך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} הרגישה מתוסכלת אחרי האימון האחרון} other {כי {name} הרגיש מתוסכל אחרי האימון האחרון}}')
where id = 'caa70203-dd20-4fd0-a2bf-43ce73caeefe';

-- feeling_positive_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'אני גאה בדרך שעשית.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סיימה את האימון האחרון בהרגשה טובה} other {כי {name} סיים את האימון האחרון בהרגשה טובה}}')
where id = 'e0d51a84-7a28-4760-8d10-7394a8a965d3';

-- feeling_positive_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {מה עזר לך להצליח? בואי נחזק את זה.} other {מה עזר לך להצליח? בוא נחזק את זה.}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סיימה את האימון האחרון בהרגשה טובה} other {כי {name} סיים את האימון האחרון בהרגשה טובה}}')
where id = '8db47520-1c8d-4c52-aab4-004dafacf8e7';

-- feeling_tired_last_session
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'גם עייפות זה בסדר. הגוף צריך לנוח.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} הרגישה עייפה אחרי האימון האחרון} other {כי {name} הרגיש עייף אחרי האימון האחרון}}')
where id = '21a1c58f-3aad-4ade-b3f4-2875e45917aa';

-- high_difficulty_reported
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'היה ממש קשה, נכון? זה בסדר להרגיש ככה.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שהאימון האחרון היה קשה מאוד} other {כי {name} סימן שהאימון האחרון היה קשה מאוד}}')
where id = '2f526750-db66-4989-9137-e00359b875d1';

-- high_total_effort_reminder
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'כל אימון שעשית חיזק אותך. ההתמדה היא ההישג.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} השלימה כבר {count} אימונים} other {כי {name} השלים כבר {count} אימונים}}')
where id = '95c778b2-aa76-4e9b-acc1-dc54744a3362';

-- improvement_between_workouts
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'ראית את ההתקדמות הקטנה? זה מה שחשוב.'),
  reason_text = jsonb_build_object('he', 'כי האימון האחרון של {name} הלך טוב יותר מהקודם')
where id = '7f5be4f7-2110-4917-af32-3b5be1906d90';

-- low_challenge_unlock_rate
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {את מתאמנת בקביעות, וזה כבר הישג.} other {אתה מתאמן בקביעות, וזה כבר הישג.}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} מתאמנת בקביעות, גם בלי הרבה אתגרים פתוחים} other {כי {name} מתאמן בקביעות, גם בלי הרבה אתגרים פתוחים}}')
where id = '933d6700-d24c-4ea1-8391-27c686c141aa';

-- low_parent_participation
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {רוצה שנתאמן יחד השבוע? תבחרי את האימון.} other {רוצה שנתאמן יחד השבוע? תבחר את האימון.}}'),
  reason_text = jsonb_build_object('he', 'כי לאחרונה כמעט לא התאמנתם יחד')
where id = 'e36ef5d7-fc7c-44e9-8b00-71aeebe2c76e';

-- negative_feeling_streak
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {איך את מרגישה עם האימונים בזמן האחרון?} other {איך אתה מרגיש עם האימונים בזמן האחרון?}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סיימה כמה אימונים ברצף בהרגשה לא טובה} other {כי {name} סיים כמה אימונים ברצף בהרגשה לא טובה}}')
where id = '97557c7a-c767-49ef-97d2-26ff9aacf7b7';

-- no_workout_3_days
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'מתי נוח לך לחזור להתאמן? ההחלטה שלך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} לא התאמנה כבר {days} ימים} other {כי {name} לא התאמן כבר {days} ימים}}')
where id = '414a3592-67df-470c-b3e4-cc250b56ff7a';

-- no_workout_7_days
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'מה יעזור לך לחזור למסלול? אני כאן איתך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} לא התאמנה כבר {days} ימים} other {כי {name} לא התאמן כבר {days} ימים}}')
where id = 'c368a084-7a36-4843-98a3-e03cfadab9bc';

-- shorter_than_average_workout
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'גם היום נחשב, כל צעד מקרב אותך.'),
  reason_text = jsonb_build_object('he', 'כי האימון האחרון של {name} היה קצר מהרגיל')
where id = 'aab3f19d-c726-4ed4-8581-065e49ae849d';

-- two_consecutive_hard_difficulty
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', 'כמה פעמים ניסית? כל ניסיון מקרב אותך.'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סימנה שני אימונים קשים ברצף} other {כי {name} סימן שני אימונים קשים ברצף}}')
where id = '511068be-421c-4bbb-834f-7ce7ff6a3133';

-- weekly_summary
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {איפה השבוע ראית את עצמך ממשיכה למרות הקושי?} other {איפה השבוע ראית את עצמך ממשיך למרות הקושי?}}'),
  reason_text = jsonb_build_object('he', '{gender, select, female {כי {name} סגרה את השבוע באימון} other {כי {name} סגר את השבוע באימון}}')
where id = 'ea930fb4-173e-4a88-8483-0278cefa71c0';

-- zero_parent_participation
update public.parent_tip_rules set
  short_text = jsonb_build_object('he', '{gender, select, female {אפשר להצטרף אלייך לאימון הבא?} other {אפשר להצטרף אליך לאימון הבא?}}'),
  reason_text = jsonb_build_object('he', 'כי עוד לא התאמנתם יחד אף פעם')
where id = 'ca4b5505-f62d-44c4-a0e8-fd8e1e12f4ef';

-- ============================================================================
-- ADDED FOR THE PARENT HOME SCREEN'S "אמרתי!"
--
-- One row each time a parent taps "אמרתי!" under a sentence on the home
-- screen: an empowerment moment. The home screen counts this month's moments,
-- keeps a sentence said today marked as done, and doesn't offer the same
-- sentence again for a week. A parent sees and adds only their own, and only
-- for a child linked to them.
-- ============================================================================

create table if not exists public.parent_tip_moments (
  id uuid primary key default gen_random_uuid(),
  parent_id uuid not null references public.parents (id) on delete cascade,
  child_id uuid not null references public.children (id) on delete cascade,
  rule_id uuid references public.parent_tip_rules (id) on delete set null,
  said_at timestamptz not null default now()
);

create index if not exists parent_tip_moments_parent_said_at
  on public.parent_tip_moments (parent_id, said_at desc);

alter table public.parent_tip_moments enable row level security;

drop policy if exists "parent_tip_moments_select_own" on public.parent_tip_moments;
create policy "parent_tip_moments_select_own" on public.parent_tip_moments
  for select using (parent_id = auth.uid());

drop policy if exists "parent_tip_moments_insert_own" on public.parent_tip_moments;
create policy "parent_tip_moments_insert_own" on public.parent_tip_moments
  for insert with check (parent_id = auth.uid() and public.is_parent_of(child_id));
